import * as Dialog from "@radix-ui/react-dialog";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, CreditCard, HandCoins, Landmark, Pencil, Plus, WalletCards, X } from "lucide-react";
import { useState } from "react";

import { api } from "../api/client";
import type { Account, AccountCreate } from "../api/types";
import { PageHeader, Panel } from "../components/layout/page";
import { Button } from "../components/ui/button";
import { Field, Input, MoneyInput, Select } from "../components/ui/field";
import { Empty, ErrorNotice, Loading } from "../components/ui/states";
import { currency } from "../lib/currency";
import { todayInSaoPaulo } from "../lib/dates";

type AccountEdit = Pick<Account, "name" | "account_type" | "account_class" | "opening_balance" | "opened_on">;

export function AccountsRoute() {
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState<Account | null>(null);
  const [editForm, setEditForm] = useState<AccountEdit>({ name: "", account_type: "checking", account_class: "asset", opening_balance: "0.00", opened_on: todayInSaoPaulo() });
  const [form, setForm] = useState<AccountCreate>({ name: "", account_type: "checking", account_class: "asset", opening_balance: "0.00", opened_on: todayInSaoPaulo() });
  const accounts = useQuery({ queryKey: ["accounts"], queryFn: () => api<Account[]>("/api/v1/accounts") });
  const create = useMutation({ mutationFn: () => api<Account>("/api/v1/accounts", { method: "POST", body: form }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["accounts"] }); setShowForm(false); setForm({ name: "", account_type: "checking", account_class: "asset", opening_balance: "0.00", opened_on: todayInSaoPaulo() }); } });
  const update = useMutation({ mutationFn: () => api<Account>(`/api/v1/accounts/${editing?.id}`, { method: "PATCH", body: editForm }), onSuccess: async () => { await queryClient.invalidateQueries(); setEditing(null); } });
  const archive = useMutation({ mutationFn: (id: string) => api<Account>(`/api/v1/accounts/${id}/archive`, { method: "POST" }), onSuccess: () => queryClient.invalidateQueries() });
  const normalizeClass = (accountType: AccountCreate["account_type"], current: AccountCreate["account_class"]) => accountType === "credit_card" ? "liability" : accountType === "receivable" ? "asset" : current;
  const setType = (accountType: AccountCreate["account_type"]) => setForm((value) => ({ ...value, account_type: accountType, account_class: normalizeClass(accountType, value.account_class) }));
  const setEditType = (accountType: AccountEdit["account_type"]) => setEditForm((value) => ({ ...value, account_type: accountType, account_class: normalizeClass(accountType, value.account_class) }));
  return <div className="page"><PageHeader eyebrow="Money containers" title="Accounts" description="Track where money lives, what you owe, and what others owe you." action={<Button onClick={() => setShowForm((value) => !value)}><Plus size={18} /> Add account</Button>} />
    {showForm ? <Panel title="New account" subtitle="Opening balance anchors your future totals."><form className="inline-form" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><Field label="Name"><Input required maxLength={100} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="e.g. Nubank or Money owed to me" /></Field><Field label="Type"><Select value={form.account_type} onChange={(event) => setType(event.target.value as AccountCreate["account_type"])}><option value="checking">Checking</option><option value="cash">Cash</option><option value="savings">Savings</option><option value="credit_card">Credit card</option><option value="receivable">Receivable</option><option value="other">Other</option></Select></Field><Field label="Balance class"><Select disabled={form.account_type === "credit_card" || form.account_type === "receivable"} value={form.account_class} onChange={(event) => setForm({ ...form, account_class: event.target.value as AccountCreate["account_class"] })}><option value="asset">Asset</option><option value="liability">Liability</option></Select></Field><Field label="Opening balance"><MoneyInput required allowNegative value={String(form.opening_balance)} onChange={(event) => setForm({ ...form, opening_balance: event.target.value })} /></Field><Field label="Opened on"><Input type="date" value={form.opened_on} onChange={(event) => setForm({ ...form, opened_on: event.target.value })} /></Field><Button type="submit" disabled={create.isPending || !form.name.trim()}>{create.isPending ? "Creating…" : "Create account"}</Button>{create.error ? <ErrorNotice message={create.error.message} /> : null}</form>{form.account_type === "receivable" ? <p className="panel-note">Use this account for money lent or purchases someone will reimburse. Transfers into it do not count as spending.</p> : form.account_type === "credit_card" ? <p className="panel-note">Record purchases as expenses on this account, then pay it with a transfer from your bank account.</p> : null}</Panel> : null}
    {accounts.isPending ? <Loading /> : accounts.error ? <ErrorNotice message={accounts.error.message} /> : accounts.data.length === 0 ? <Empty title="No accounts yet" body="Create the account you use most to start recording transactions." /> : <section className="account-grid">{accounts.data.map((item) => { const Icon = item.account_type === "credit_card" ? CreditCard : item.account_type === "receivable" ? HandCoins : item.account_type === "cash" ? WalletCards : Landmark; const owed = item.account_class === "liability"; return <article className="account-card" key={item.id}><div className="account-card-head"><span><Icon /></span><div className="row-actions"><Button variant="ghost" size="icon" title="Edit account" onClick={() => { setEditForm({ name: item.name, account_type: item.account_type, account_class: item.account_class, opening_balance: item.opening_balance, opened_on: item.opened_on }); setEditing(item); }}><Pencil size={16} /></Button><Button variant="ghost" size="icon" title="Archive account" onClick={() => archive.mutate(item.id)}><Archive size={17} /></Button></div></div><small>{item.account_type.replace("_", " ")}</small><h2>{item.name}</h2><div><span>{owed ? "Amount owed" : item.account_type === "receivable" ? "Still owed to you" : "Current balance"}</span><strong>{currency(owed ? Math.abs(Number(item.current_balance)) : item.current_balance, item.currency)}</strong></div><p>Opened with {currency(item.opening_balance, item.currency)}</p></article>; })}</section>}
    <Dialog.Root open={editing !== null} onOpenChange={(open) => { if (!open) setEditing(null); }}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog-content"><div className="dialog-heading"><div><span className="eyebrow">Account details</span><Dialog.Title>Edit account</Dialog.Title></div><Dialog.Close asChild><Button variant="ghost" size="icon" aria-label="Close"><X size={20} /></Button></Dialog.Close></div><Dialog.Description className="muted">Correct its name, type, balance class, or opening information.</Dialog.Description><form className="form-grid" onSubmit={(event) => { event.preventDefault(); update.mutate(); }}><Field label="Name"><Input required maxLength={100} value={editForm.name} onChange={(event) => setEditForm({ ...editForm, name: event.target.value })} /></Field><Field label="Type"><Select value={editForm.account_type} onChange={(event) => setEditType(event.target.value as AccountEdit["account_type"])}><option value="checking">Checking</option><option value="cash">Cash</option><option value="savings">Savings</option><option value="credit_card">Credit card</option><option value="receivable">Receivable</option><option value="other">Other</option></Select></Field><Field label="Balance class"><Select disabled={editForm.account_type === "credit_card" || editForm.account_type === "receivable"} value={editForm.account_class} onChange={(event) => setEditForm({ ...editForm, account_class: event.target.value as AccountEdit["account_class"] })}><option value="asset">Asset</option><option value="liability">Liability</option></Select></Field>{editForm.account_type === "credit_card" ? <p className="form-helper">Credit cards are always liabilities.</p> : editForm.account_type === "receivable" ? <p className="form-helper">Receivables are always assets.</p> : null}<Field label="Opening balance"><MoneyInput required allowNegative value={editForm.opening_balance} onChange={(event) => setEditForm({ ...editForm, opening_balance: event.target.value })} /></Field><p className="form-helper warning">Changing the opening balance recalculates the account’s entire history.</p><Field label="Opened on"><Input type="date" value={editForm.opened_on} onChange={(event) => setEditForm({ ...editForm, opened_on: event.target.value })} /></Field>{update.error ? <ErrorNotice message={update.error.message} /> : null}<Button type="submit" size="lg" disabled={update.isPending || !editForm.name.trim()}>{update.isPending ? "Saving…" : "Save account"}</Button></form></Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}
