import * as Dialog from "@radix-ui/react-dialog";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Clock3, Pencil, Plus, SkipForward, X } from "lucide-react";
import { useMemo, useState } from "react";

import { api } from "../api/client";
import type { Account, Category, Recurring, RecurringCreate } from "../api/types";
import { PageHeader, Panel } from "../components/layout/page";
import { Button } from "../components/ui/button";
import { Field, Input, MoneyInput, Select } from "../components/ui/field";
import { Empty, ErrorNotice, Loading } from "../components/ui/states";
import { currency } from "../lib/currency";
import { displayDate, todayInSaoPaulo } from "../lib/dates";

export function RecurringRoute() {
  const queryClient = useQueryClient(); const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState<Recurring | null>(null);
  const [editForm, setEditForm] = useState({ amount: "", description: "", notes: "", end_on: "", active: true });
  const [form, setForm] = useState<RecurringCreate>({ kind: "expense", account_id: "", category_id: "", amount: "", description: "", notes: null, frequency: "monthly", interval_count: 1, start_on: todayInSaoPaulo(), end_on: null });
  const templates = useQuery({ queryKey: ["recurring"], queryFn: () => api<Recurring[]>("/api/v1/recurring-templates") });
  const accounts = useQuery({ queryKey: ["accounts"], queryFn: () => api<Account[]>("/api/v1/accounts") });
  const categories = useQuery({ queryKey: ["categories"], queryFn: () => api<Category[]>("/api/v1/categories") });
  const matchingCategories = useMemo(() => categories.data?.filter((item) => item.kind === form.kind) ?? [], [categories.data, form.kind]);
  const create = useMutation({ mutationFn: () => api<Recurring>("/api/v1/recurring-templates", { method: "POST", body: form }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["recurring"] }); await queryClient.invalidateQueries({ queryKey: ["dashboard"] }); setShowForm(false); } });
  const update = useMutation({ mutationFn: () => api<Recurring>(`/api/v1/recurring-templates/${editing?.id}`, { method: "PATCH", body: { amount: editForm.amount, description: editForm.description, notes: editForm.notes || null, end_on: editForm.end_on || null, active: editForm.active } }), onSuccess: async () => { await queryClient.invalidateQueries(); setEditing(null); } });
  const handle = useMutation({ mutationFn: ({ item, action }: { item: Recurring; action: "record" | "skip" }) => action === "record" ? api(`/api/v1/recurring-templates/${item.id}/occurrences`, { method: "POST", body: { scheduled_for: item.next_due_on } }) : api(`/api/v1/recurring-templates/${item.id}/occurrences/${item.next_due_on}/skip`, { method: "POST" }), onSuccess: () => queryClient.invalidateQueries() });
  return <div className="page"><PageHeader eyebrow="Expected money" title="Recurring" description="Keep expectations separate from actual transactions until you confirm them." action={<Button onClick={() => setShowForm((value) => !value)}><Plus size={17} /> Add recurring</Button>} />
    {showForm ? <Panel title="New recurring expectation"><form className="inline-form" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><Field label="Type"><Select value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value as RecurringCreate["kind"], category_id: "" })}><option value="expense">Expense</option><option value="income">Income</option></Select></Field><Field label="Description"><Input required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="e.g. Rent" /></Field><Field label="Amount"><MoneyInput required value={String(form.amount)} onChange={(event) => setForm({ ...form, amount: event.target.value })} /></Field><Field label="Account"><Select required value={form.account_id} onChange={(event) => setForm({ ...form, account_id: event.target.value })}><option value="">Choose account</option>{accounts.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Category"><Select required value={form.category_id} onChange={(event) => setForm({ ...form, category_id: event.target.value })}><option value="">Choose category</option>{matchingCategories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Frequency"><Select value={form.frequency} onChange={(event) => setForm({ ...form, frequency: event.target.value as RecurringCreate["frequency"] })}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></Select></Field><Field label="First due date"><Input type="date" value={form.start_on} onChange={(event) => setForm({ ...form, start_on: event.target.value })} /></Field><Button type="submit" disabled={create.isPending}>{create.isPending ? "Creating…" : "Create expectation"}</Button>{create.error ? <ErrorNotice message={create.error.message} /> : null}</form></Panel> : null}
    {templates.isPending ? <Loading /> : templates.error ? <ErrorNotice message={templates.error.message} /> : templates.data.length === 0 ? <Empty title="Nothing recurring yet" body="Add rent, salary, subscriptions, or other expected movements." /> : <div className="recurring-list">{templates.data.map((item) => <article key={item.id}><span className={`recurring-icon ${item.kind}`}><Clock3 /></span><div><h2>{item.description}</h2><p>{item.frequency}{item.interval_count > 1 ? ` · every ${item.interval_count}` : ""} · next {displayDate(item.next_due_on)}</p></div><strong>{item.kind === "expense" ? "−" : "+"}{currency(item.amount)}</strong><div className="row-actions"><Button variant="ghost" size="icon" aria-label={`Edit ${item.description}`} onClick={() => { setEditForm({ amount: item.amount, description: item.description, notes: item.notes ?? "", end_on: item.end_on ?? "", active: item.active }); setEditing(item); }}><Pencil size={15} /></Button><Button variant="secondary" size="sm" onClick={() => handle.mutate({ item, action: "skip" })}><SkipForward size={15} /> Skip</Button><Button size="sm" onClick={() => handle.mutate({ item, action: "record" })}><Check size={15} /> Record</Button></div></article>)}</div>}
    <Dialog.Root open={editing !== null} onOpenChange={(open) => { if (!open) setEditing(null); }}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog-content"><div className="dialog-heading"><div><span className="eyebrow">Expected money</span><Dialog.Title>Edit recurring expectation</Dialog.Title></div><Dialog.Close asChild><Button variant="ghost" size="icon" aria-label="Close"><X size={20} /></Button></Dialog.Close></div><Dialog.Description className="muted">Changes affect future occurrences only.</Dialog.Description><form className="form-grid" onSubmit={(event) => { event.preventDefault(); update.mutate(); }}><Field label="Description"><Input required value={editForm.description} onChange={(event) => setEditForm({ ...editForm, description: event.target.value })} /></Field><Field label="Amount"><MoneyInput required value={editForm.amount} onChange={(event) => setEditForm({ ...editForm, amount: event.target.value })} /></Field><Field label="End date"><Input type="date" value={editForm.end_on} onChange={(event) => setEditForm({ ...editForm, end_on: event.target.value })} /></Field><Field label="Note"><Input value={editForm.notes} onChange={(event) => setEditForm({ ...editForm, notes: event.target.value })} /></Field><label className="checkbox-row"><input type="checkbox" checked={editForm.active} onChange={(event) => setEditForm({ ...editForm, active: event.target.checked })} /> Active</label>{update.error ? <ErrorNotice message={update.error.message} /> : null}<Button type="submit" size="lg" disabled={update.isPending || !editForm.description.trim()}>{update.isPending ? "Saving…" : "Save expectation"}</Button></form></Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}
